typography_spectrum: 0.3109
color:
  brandStrength: 0.75
  saturation: 0.6875
  brandColors:
    - '#000000'
    - '#b75a2f'
    - '#ceb36c'
    - '#3f1f10'
    - '#bc6e3c'
  lightness: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6727159
analytics:
  twitter: null
  google: null
  facebook: null
name: oelkemedia
cta:
  version: null
  bucket: null
  domain: null
navigation:
  - id: 'http://www.theprivatesession.com'
    url: 'http://www.theprivatesession.com'
    name: The Private Session
    type: external
  - id: 'http://www.brigitteoelke.com/News/'
    url: 'http://www.brigitteoelke.com/News/'
    name: brigitteoelke.com
    type: external
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Brigitte Oelke in den Medien
purpose: []
