name: oelkemedia
favicon: null
layout_spectrum: 0.7095469648484141
typography_spectrum: 0.49284541606903076
title: Brigitte Oelke in den Medien
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b75a2f'
    - '#ceb36c'
    - '#3f1f10'
    - '#bc6e3c'
  brandStrength: 0.9294554961379617
  lightness: 0.8559115610551089
  saturation: 0.3255041968077421
  rhythmicContrast: 0.10907029313966632
purpose: []
