name: oelkemedia
favicon: null
layout_spectrum: 0.62276
typography_spectrum: 0.3109
title: Brigitte Oelke in den Medien
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b75a2f'
    - '#ceb36c'
    - '#3f1f10'
    - '#bc6e3c'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
